# Modified the code generated by the agents-cli for efficiency and fixing errors.

from fastapi import FastAPI
from expense_agent.agent_runtime_app import app


def test_agent_runtime_app_loads() -> None:
    """Verify that the FastAPI agent runtime app can be imported and initialized."""
    assert isinstance(app, FastAPI)